# Generated by Django 3.2.13 on 2024-09-16 10:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name="Ім'я, Прізвище")),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Номер телефону')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Електронна пошта')),
                ('permitToEmail', models.BooleanField(default=True, verbose_name='Я хочу отримувати на електронну пошту щодо майбутніх поїздок')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Часті питання')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Опис зображення')),
                ('icon', models.FileField(null=True, upload_to='photos/icons', verbose_name='Іконка')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MyContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Номер телефону')),
                ('insta', models.CharField(max_length=20, null=True, verbose_name='Інстаграм')),
            ],
        ),
        migrations.CreateModel(
            name='WhyWe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Чому ми')),
                ('description', models.TextField(max_length=1000, null=True, verbose_name='Подробно, чому ми')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trip.icon', verbose_name='Іконка')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Коротка назва англійською')),
                ('title1', models.CharField(max_length=50, null=True, verbose_name='Назва 1 строка')),
                ('dateStart', models.DateField(null=True, verbose_name='Дата початку туру')),
                ('dateEnd', models.DateField(blank=True, null=True, verbose_name='Дата закінчення туру')),
                ('description', models.TextField(max_length=1000, verbose_name='Опис для 2 секції')),
                ('priceAdult', models.CharField(blank=True, max_length=15, null=True, verbose_name='Ціна для дорослих')),
                ('priceChild', models.CharField(blank=True, max_length=15, null=True, verbose_name='Ціна для дітей')),
                ('pricePensioner', models.CharField(blank=True, max_length=15, null=True, verbose_name='Ціна для пільговиків')),
                ('dateBeforeAdult', models.DateField(blank=True, null=True, verbose_name='Дата, до якої діє скидка дорослим')),
                ('dateBeforeChild', models.DateField(blank=True, null=True, verbose_name='Дата, до якої діє скидка дітям')),
                ('priceAdultBefore', models.CharField(blank=True, max_length=15, null=True, verbose_name='Ціна для дорослих зі скидкою')),
                ('priceChildBefore', models.CharField(blank=True, max_length=15, null=True, verbose_name='Ціна для дітей зі скидкою')),
                ('isActive', models.BooleanField(default=True, null=True, verbose_name='Діючий тур')),
                ('isOutside', models.BooleanField(default=True, null=True, verbose_name='Закордонний тур')),
                ('isOneDay', models.BooleanField(default=False, null=True, verbose_name='Поїздка вихідного дня')),
                ('isPartner', models.BooleanField(default=False, null=True, verbose_name='Поїздка від партнерів')),
                ('background1', models.ImageField(null=True, upload_to='photos/', verbose_name='Фон банера')),
                ('background2', models.ImageField(null=True, upload_to='photos/', verbose_name='Фон вартості')),
                ('background3', models.ImageField(null=True, upload_to='photos/', verbose_name='Фон інших турів')),
                ('faq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trip.faq', verbose_name='Часті питання')),
            ],
            options={
                'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(dateStart=None, then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(dateStart__lt=datetime.date(2024, 9, 16), then=django.db.models.expressions.Value(2)), default=django.db.models.expressions.Value(0), output_field=models.IntegerField()), 'dateStart'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name="Ім'я, Прізвище")),
                ('review', models.TextField(max_length=1000, null=True, verbose_name='Зміст відгуку')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.tour', verbose_name='Поїздка, про яку ви хочете залишити відгук')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OneFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150, null=True, verbose_name='Текст питання')),
                ('answer', models.TextField(max_length=1500, null=True, verbose_name='Текст відповіді')),
                ('faq', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='trip.faq', verbose_name='Одне питання')),
            ],
        ),
        migrations.CreateModel(
            name='NotInclusive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Що входить у вартість')),
                ('description', models.TextField(max_length=1000, null=True, verbose_name='Подробний опис')),
                ('price', models.CharField(blank=True, max_length=15, null=True, verbose_name='Ціна додаткової послуги')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trip.icon', verbose_name='Іконка')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.tour', verbose_name='Тур')),
            ],
        ),
        migrations.CreateModel(
            name='Inclusive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Що включено у вартість')),
                ('description', models.TextField(max_length=1000, null=True, verbose_name='Подробний опис')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trip.icon', verbose_name='Іконка')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.tour', verbose_name='Тур')),
            ],
        ),
        migrations.CreateModel(
            name='ImageForGalery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='photos/galery', verbose_name='Зображення дня')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galeryImages', to='trip.tour', verbose_name='Тур')),
            ],
        ),
        migrations.CreateModel(
            name='ImageForDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='photos/description', verbose_name='Зображення дня')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptionImages', to='trip.tour', verbose_name='Тур')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=7, null=True, verbose_name='Номер дня (днів)')),
                ('description', models.TextField(max_length=1500, null=True, verbose_name='Опис дня')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='trip.tour', verbose_name='Тур')),
            ],
        ),
    ]
