# Generated by Django 3.2.13 on 2024-09-22 14:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(dateStart=None, then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(dateStart__lt=datetime.date(2024, 9, 22), then=django.db.models.expressions.Value(2)), default=django.db.models.expressions.Value(0), output_field=models.IntegerField()), 'dateStart']},
        ),
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='Часті питання'),
        ),
        migrations.CreateModel(
            name='FaqTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trip.faq', verbose_name='Питання')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='trip.tour', verbose_name='Тур')),
            ],
        ),
    ]
