# Generated by Django 3.2.13 on 2024-10-16 16:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20240922_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=0, default=50, max_digits=3, null=True, verbose_name='% передплати')),
            ],
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(dateStart=None, then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(dateStart__lt=datetime.date(2024, 10, 16), then=django.db.models.expressions.Value(2)), default=django.db.models.expressions.Value(0), output_field=models.IntegerField()), 'dateStart']},
        ),
        migrations.AddField(
            model_name='client',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3, null=True, verbose_name='Кількість осіб'),
        ),
        migrations.AddField(
            model_name='client',
            name='children',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, null=True, verbose_name='в т.ч. дітей'),
        ),
        migrations.AddField(
            model_name='client',
            name='myNotes',
            field=models.TextField(max_length=1000, null=True, verbose_name='Примітки адміністратора'),
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(max_length=1000, null=True, verbose_name='Примітки'),
        ),
        migrations.AddField(
            model_name='client',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='trip.payment', verbose_name='Передплата'),
        ),
    ]
