# Generated by Django 3.2.13 on 2024-10-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_auto_20241016_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Назва дня'),
        ),
    ]
