# Generated by Django 3.2.13 on 2024-11-06 12:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_day_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lifehack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Назва лайфхаку')),
            ],
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(dateStart=None, then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(dateStart__lt=datetime.date(2024, 11, 6), then=django.db.models.expressions.Value(2)), default=django.db.models.expressions.Value(0), output_field=models.IntegerField()), 'dateStart']},
        ),
        migrations.CreateModel(
            name='CardForLifehack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='photos/lifehacks', verbose_name='Зображення лайфхаку')),
                ('lifehack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='trip.lifehack', verbose_name='Лайфхак')),
            ],
        ),
    ]
