# Generated by Django 3.2.13 on 2024-11-09 19:40

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_auto_20241106_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(dateStart=None, then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(dateStart__lt=datetime.date(2024, 11, 9), then=django.db.models.expressions.Value(2)), default=django.db.models.expressions.Value(0), output_field=models.IntegerField()), 'dateStart']},
        ),
        migrations.AddField(
            model_name='client',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Схвалено'),
        ),
    ]
