# Generated by Django 3.2.13 on 2024-11-12 14:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0007_auto_20241110_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name="Ім'я та Прізвище, для кого подарунок")),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Номер телефону')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=9, null=True, verbose_name='Сума подарунку у грн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата замовлення')),
                ('valid_until', models.DateTimeField(null=True, verbose_name='Сертифікат дійсний до')),
                ('code', models.DecimalField(decimal_places=0, default=0, max_digits=9, null=True, verbose_name='Унікальний код сертифіката')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Електронна пошта')),
                ('approved', models.BooleanField(default=False, verbose_name='Схвалено')),
            ],
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(dateStart=None, then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(dateStart__lt=datetime.date(2024, 11, 12), then=django.db.models.expressions.Value(2)), default=django.db.models.expressions.Value(0), output_field=models.IntegerField()), 'dateStart']},
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='myNotes',
        ),
        migrations.RemoveField(
            model_name='client',
            name='permitToEmail',
        ),
        migrations.AddField(
            model_name='client',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='trip.tour', verbose_name='Подорож'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name="Ім'я, Прізвище"),
        ),
        migrations.AlterField(
            model_name='client',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='trip.payment', verbose_name='Оберіть відсоток передплати'),
        ),
    ]
