# Generated by Django 3.2.13 on 2024-11-12 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0008_auto_20241112_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)], verbose_name='Сума подарунку у грн'),
        ),
    ]
