# Generated by Django 3.2.13 on 2024-11-14 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0010_auto_20241114_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=15, null=True, verbose_name='Валюта')),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trip.currency', verbose_name='Валюта'),
        ),
    ]
