# Generated by Django 3.2.13 on 2024-12-10 12:03

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0011_auto_20241114_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(dateStart=None, then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(dateStart__lt=datetime.date(2024, 12, 10), then=django.db.models.expressions.Value(2)), default=django.db.models.expressions.Value(0), output_field=models.IntegerField()), 'dateStart']},
        ),
        migrations.AddField(
            model_name='tour',
            name='seats',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9, null=True, verbose_name='Кількість місць'),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Примітки'),
        ),
    ]
