# Generated by Django 3.2.13 on 2024-12-16 13:10

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0012_auto_20241210_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(dateStart=None, then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(dateStart__lt=datetime.date(2024, 12, 16), then=django.db.models.expressions.Value(2)), default=django.db.models.expressions.Value(0), output_field=models.IntegerField()), 'dateStart']},
        ),
        migrations.AddField(
            model_name='mycontacts',
            name='aboutme1',
            field=models.TextField(max_length=1000, null=True, verbose_name='Про мене 1'),
        ),
        migrations.AddField(
            model_name='mycontacts',
            name='aboutme2',
            field=models.TextField(max_length=1000, null=True, verbose_name='Про мене 2'),
        ),
        migrations.AddField(
            model_name='mycontacts',
            name='aboutme3',
            field=models.TextField(max_length=1000, null=True, verbose_name='Про мене 3'),
        ),
        migrations.AddField(
            model_name='mycontacts',
            name='photo1',
            field=models.ImageField(null=True, upload_to='photos/', verbose_name='Моє фото 1'),
        ),
        migrations.AddField(
            model_name='mycontacts',
            name='photo2',
            field=models.ImageField(null=True, upload_to='photos/', verbose_name='Моє фото 2'),
        ),
        migrations.AddField(
            model_name='mycontacts',
            name='photo3',
            field=models.ImageField(null=True, upload_to='photos/', verbose_name='Моє фото 3'),
        ),
        migrations.AddField(
            model_name='mycontacts',
            name='photo4',
            field=models.ImageField(null=True, upload_to='photos/', verbose_name='Моє фото 4'),
        ),
        migrations.AddField(
            model_name='mycontacts',
            name='telegram',
            field=models.CharField(max_length=30, null=True, verbose_name='Телеграм'),
        ),
        migrations.AddField(
            model_name='mycontacts',
            name='telegramChannel',
            field=models.CharField(max_length=30, null=True, verbose_name='Телеграм канал'),
        ),
        migrations.AddField(
            model_name='mycontacts',
            name='viber',
            field=models.CharField(max_length=30, null=True, verbose_name='Вайбер'),
        ),
        migrations.AddField(
            model_name='mycontacts',
            name='whatsapp',
            field=models.CharField(max_length=30, null=True, verbose_name='Ватсап'),
        ),
        migrations.AlterField(
            model_name='mycontacts',
            name='insta',
            field=models.CharField(max_length=30, null=True, verbose_name='Інстаграм'),
        ),
        migrations.AlterField(
            model_name='mycontacts',
            name='phone',
            field=models.CharField(max_length=30, null=True, verbose_name='Номер телефону'),
        ),
    ]
