# Generated by Django 3.2.13 on 2024-12-26 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0014_auto_20241226_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='communication',
        ),
        migrations.AddField(
            model_name='client',
            name='communication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trip.communication', verbose_name='Куди Вам дзвонити / писати?'),
        ),
    ]
