# Generated by Django 3.2.13 on 2025-01-13 11:13

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0015_auto_20241226_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(dateStart=None, then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(dateStart__lt=datetime.date(2025, 1, 13), then=django.db.models.expressions.Value(2)), default=django.db.models.expressions.Value(0), output_field=models.IntegerField()), 'dateStart']},
        ),
        migrations.AddField(
            model_name='client',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата початку туру'),
        ),
        migrations.AddField(
            model_name='client',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Видалено'),
        ),
        migrations.AlterField(
            model_name='mycontacts',
            name='insta',
            field=models.CharField(max_length=50, null=True, verbose_name='Інстаграм'),
        ),
        migrations.AlterField(
            model_name='mycontacts',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='mycontacts',
            name='telegram',
            field=models.CharField(max_length=50, null=True, verbose_name='Телеграм'),
        ),
        migrations.AlterField(
            model_name='mycontacts',
            name='telegramChannel',
            field=models.CharField(max_length=500, null=True, verbose_name='Телеграм канал'),
        ),
        migrations.AlterField(
            model_name='mycontacts',
            name='viber',
            field=models.CharField(max_length=50, null=True, verbose_name='Вайбер'),
        ),
        migrations.AlterField(
            model_name='mycontacts',
            name='whatsapp',
            field=models.CharField(max_length=50, null=True, verbose_name='Ватсап'),
        ),
    ]
