# Generated by Django 3.2.13 on 2025-01-16 09:52

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0016_auto_20250113_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(dateStart=None, then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(dateStart__lt=datetime.date(2025, 1, 16), then=django.db.models.expressions.Value(2)), default=django.db.models.expressions.Value(0), output_field=models.IntegerField()), 'dateStart']},
        ),
        migrations.AddField(
            model_name='tour',
            name='descriptionPdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Опис у форматі PDF'),
        ),
    ]
