# Generated by Django 3.2.13 on 2025-01-22 10:00

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0018_auto_20250117_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(dateStart=None, then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(dateStart__lt=datetime.date(2025, 1, 22), then=django.db.models.expressions.Value(2)), default=django.db.models.expressions.Value(0), output_field=models.IntegerField()), 'dateStart']},
        ),
        migrations.AddField(
            model_name='certificate',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Відпрацьовано'),
        ),
        migrations.AlterField(
            model_name='onefaq',
            name='answer',
            field=models.TextField(max_length=3000, null=True, verbose_name='Текст відповіді'),
        ),
    ]
