# Generated by Django 3.2.13 on 2025-02-01 18:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0019_auto_20250122_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, null=True, verbose_name='Тип додаткової послуги')),
            ],
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(dateStart=None, then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(dateStart__lt=datetime.date(2025, 2, 1), then=django.db.models.expressions.Value(2)), default=django.db.models.expressions.Value(0), output_field=models.IntegerField()), 'dateStart']},
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name="Ім'я та Прізвище, для кого подарунок")),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Ваш номер телефону')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата замовлення')),
                ('completed', models.BooleanField(default=False, verbose_name='Відпрацьовано')),
                ('communication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trip.communication', verbose_name='Куди Вам дзвонити / писати?')),
                ('extraType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extraTypes', to='trip.extratype', verbose_name='Тип додаткової послуги')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
