# Generated by Django 3.2.13 on 2025-02-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0021_alter_tour_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycontacts',
            name='titleAboutMe',
            field=models.CharField(max_length=100, null=True, verbose_name='Title для сторінки Про мене'),
        ),
        migrations.AddField(
            model_name='mycontacts',
            name='titleAnswers',
            field=models.CharField(max_length=100, null=True, verbose_name='Title для сторінки з відповідями'),
        ),
        migrations.AddField(
            model_name='mycontacts',
            name='titleDocuments',
            field=models.CharField(max_length=100, null=True, verbose_name='Title для документів'),
        ),
        migrations.AddField(
            model_name='mycontacts',
            name='titleExtras',
            field=models.CharField(max_length=100, null=True, verbose_name='Title для додаткових послуг'),
        ),
        migrations.AddField(
            model_name='mycontacts',
            name='titleFAQ',
            field=models.CharField(max_length=100, null=True, verbose_name='Для всіх FAQ'),
        ),
        migrations.AddField(
            model_name='mycontacts',
            name='titleGalery',
            field=models.CharField(max_length=100, null=True, verbose_name='Title для галереї'),
        ),
        migrations.AddField(
            model_name='mycontacts',
            name='titleIndex',
            field=models.CharField(max_length=100, null=True, verbose_name='Title для домашньої сторінки'),
        ),
        migrations.AddField(
            model_name='mycontacts',
            name='titleLifehacks',
            field=models.CharField(max_length=100, null=True, verbose_name='Title для сторінки з лайфхаками'),
        ),
        migrations.AddField(
            model_name='mycontacts',
            name='titleReviews',
            field=models.CharField(max_length=100, null=True, verbose_name='Title для сторінки відгуків'),
        ),
        migrations.AddField(
            model_name='mycontacts',
            name='titleUseful',
            field=models.CharField(max_length=100, null=True, verbose_name='Title для сторінки з корисним'),
        ),
    ]
